/** Declaration file generated by dts-gen */

export = tomlify;

declare function tomlify(value: any, replacer?: Function, space?: string | number): string;

declare namespace tomlify {
    function toToml(value: any, replacer?: Function, space?: string | number): string;

    function toValue(value: any, replacer?: Function, space?: string | number): string;
    
    function toKey(path: string | Array<string | number>, alternative: boolean): string;
}